[package]
name = "perf-sched-plot"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
textplots = "0.8.6"
winnow = "0.6.20"

[dev-dependencies]
winnow = { version = "0.6.20", features = ["debug"] }
